version: "3"
services: 
  casey:
    container_name: 'casey'
    build: 
      dockerfile: ./build/docker/Casey/Dockerfile
      context: .
    networks:
      - general
    depends_on:
      - 'rabbitmq'
    restart: 'on-failure'
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    ports:
    - "5672:5672"
    - "15672:15672"
    logging:
      driver: none
    networks:
      - general
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
networks:
  general:
    driver: bridge
